apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcg-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcg-frontend
  template:
    metadata:
      labels:
        app: tcg-frontend
    spec:
      containers:
      - name: frontend-container
        image: abdillah11/frontend:latest 
        ports:
        - containerPort: 80
        # --- TAMBAHKAN BAGIAN INI ---
        env:
        - name: NAMA
          value: "Abdillah"
        - name: NIM
          value: "2408515"
        # ----------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP 
  selector:
    app: tcg-frontend
  ports:
  - port: 80
    targetPort: 80